### ISSUE TITLE
bug：it was choked but only finished half of  work. it still like this after one day！

### ISSUE THREAD

**Issue by zer0yu** [x90skysn3k/brutespray#12]
![123](https://user-images.githubusercontent.com/16551733/29237828-5cea4962-7f59-11e7-85e6-2668497a0480.png)

**Comment by jrobles-r7** [comment]
Your connections are probably being dropped or throttled by the host you are scanning (or an intermediate device). After the nmap output parsing completes, medusa mostly takes over.
