### ISSUE TITLE
no module named readline

### ISSUE THREAD

**Issue by ayste** [x90skysn3k/brutespray#15]
i have a problem when i tap (python brutespray.py) 
and it display (
Traceback (most recent call last):
  File "brutespray.py", line 4, in <module>
    import readline, glob
ImportError: No module named readline        )

**Comment by bcoles** [comment]
```bash
pip install -r requirements.txt
```

**Comment by x90skysn3k** [comment]
try 
`sudo apt-get install libncurses5-dev`

then 

`pip install readline`

**Comment by qrasulee** [comment]
I had this issue on Kali linux. 

sudo apt-get install libncurses5-dev

then 

sudo -H pip3 install readline

**Comment by x90skysn3k** [comment]
just do:
`apt install brutespray`
