### ISSUE TITLE
program waiting longtime , some errors username

### ISSUE THREAD

**Issue by kafire** [x90skysn3k/brutespray#16]
root@kali:~/src/nmap/brutespray/brutespray-output# more telnet-success.txt
[+] ACCOUNT FOUND: [telnet] Host: x.29.139.93 User: [E2][80][93] Password: 0P3N [SUCCESS]
[+] ACCOUNT FOUND: [telnet] Host: x.29.139.93 User: [E2][80][93] Password: 1064 [SUCCESS]
[+] ACCOUNT FOUND: [telnet] Host: x.29.139.93 User: [E2][80][93] Password: 10023 [SUCCESS]
[+] ACCOUNT FOUND: [telnet] Host: x.29.139.93 User: [E2][80][93] Password: 0 [SUCCESS]
[+] ACCOUNT FOUND: [telnet] Host: x.29.139.93 User: [E2][80][93] Password: 1111 [SUCCESS]

**Comment by kafire** [comment]
'

**Comment by x90skysn3k** [comment]
depending on the output of the telnet session, this will cause Medusa to create some false positives in it's logic. Since BruteSpray uses Medusa as it's backbone, this issue will have to be brought up to the Medusa Team.
