### ISSUE TITLE
No such file or directory: error

### ISSUE THREAD

**Issue by tokyoneon** [x90skysn3k/brutespray#18]
Hey guys, can you write in some way to gracefully deal with "No such file" errors when users (shamefully) point to a file that no longer exist?
	 
	 
	 brutespray.py v1.6.0
	 Created by: Shane Young/@x90skysn3k && Jacob Robles/@shellfail
	 Inspired by: Leon Johnson/@sho-luv
	 Credit to Medusa: JoMo-Kun / Foofus Networks <jmk@foofus.net>

	Traceback (most recent call last):
	  File "/usr/bin/brutespray", line 365, in <module>
		make_dic_gnmap()
	  File "/usr/bin/brutespray", line 134, in make_dic_gnmap
		with open(args.file, 'r') as nmap_file:
	IOError: [Errno 2] No such file or directory: '/root/Desktop/brutespray.xml'
	Loading File: |^C

The Brutespray terminal freezes and pressing _Ctrl_ + _c_ doesn't work. I had to forcefully kill the PID.

**Comment by x90skysn3k** [comment]
fixed with commit 687f46e, sorry for the problems
