### ISSUE TITLE
False Positive Telnet Results

### ISSUE THREAD

**Issue by superhedgy** [x90skysn3k/brutespray#33]
Hi I have been testing it against a bunch of HP printers with telnet services.

I have got the following results which I was not able to verify:

```
# cat telnet-success.txt 
[+] ACCOUNT FOUND: [telnet] Host: xxx User: [E2][80][93] Password: 0 [SUCCESS]
[+] ACCOUNT FOUND: [telnet] Host: xxx User: [E2][80][93] Password: 0 [SUCCESS]
[+] ACCOUNT FOUND: [telnet] Host: xxx User: [E2][80][93] Password: 0P3N [SUCCESS]
[+] ACCOUNT FOUND: [telnet] Host: xxx User: [E2][80][93] Password: 0P3N [SUCCESS]
....
```

After digging up a bit E2 80 93 is the hex characters in UTF-8 encoding for dash "-".

**Comment by superhedgy** [comment]
It appears to be a Medusa bug. I will raise it on their git.

**Comment by x90skysn3k** [comment]
cool thanks, yeah when medusa sees output back it counts as a success
