### ISSUE TITLE
CRITICAL: Unknown rlogin.mod module state -1

### ISSUE THREAD

**Issue by Spacewalker2** [x90skysn3k/brutespray#34]
Hello,

I get the error message below but not sure what it really means. I use version 1.6.4 of brutespray. I know 1.6.6 is the newest so I checked the changelog and decide to post this anyway.

```
CRITICAL: Unknown rlogin.mod module state -1
ERROR: rlogin.mod failed: medusaReceive returned no data.
```

Thanks for such a create tool!

**Comment by x90skysn3k** [comment]
that is a medusa error, make sure you installed correctly
