### ISSUE TITLE
Failed to open ...

### ISSUE THREAD

**Issue by Chechene** [x90skysn3k/brutespray#37]
It seems like Brutespray tries to open /usr/share/brutespray/wordlist/[service]/user.
But the wordlists are all in ~/brutespray/wordlist/[service]/ , not in /usr/share/brutespray/wordlist/[service]/user.

my command was : `./brutespray.py -t 10 --file test.xml`

here the err msg:
`Brute-Forcing...     
FATAL: Failed to open file /usr/share/brutespray/wordlist/ssh/user - No such file or directory
FATAL: Failed to open file /usr/share/brutespray/wordlist/smtp/user - No such file or directory
FATAL: Failed to open file /usr/share/brutespray/wordlist/mysql/user - No such file or directory
FATAL: Failed to open file /usr/share/brutespray/wordlist/smbnt/user - No such file or directory
FATAL: Failed to open file /usr/share/brutespray/wordlist/telnet/user - No such file or directory
FATAL: Failed to open file /usr/share/brutespray/wordlist/rlogin/user - No such file or directory
FATAL: Failed to open file /usr/share/brutespray/wordlist/postgres/user - No such file or directory
FATAL: Failed to open file /usr/share/brutespray/wordlist/rexec/user - No such file or directory
FATAL: Failed to open file /usr/share/brutespray/wordlist/ftp/user - No such file or directory
FATAL: Failed to open file /usr/share/brutespray/wordlist/vnc/user - No such file or directory`

**Comment by x90skysn3k** [comment]
Do you have read permissions to those files?

**Comment by x90skysn3k** [comment]
fixed with https://github.com/x90skysn3k/brutespray/commit/d8e593a4908bd8f786cfd3ede9981a42d5f499b7
