### ISSUE TITLE
How can I convert nmap .xml output to .gnmap?

### ISSUE THREAD

**Issue by crossmxn** [x90skysn3k/brutespray#4]
Sorry, I know this is not a bug but I couldn't find anything on Google. Is there a way to convert my .xml outputs to .gnmap? Thanks and sorry for taking a bit of your time.

**Comment by x90skysn3k** [comment]
hey sorry for the late reply, at this time there isn't an easy way to convert XML to GNMAP, i am looking to add functionality to read XML files

**Comment by x90skysn3k** [comment]
hey man, i wrote the functionality to use nmap XML  - closing

**Comment by crossmxn** [comment]
Thanks a freaking lot! I didn't expected you to go this far. Really really really thank you :)

**Comment by x90skysn3k** [comment]
Oh heck yeah man, no prob.. xml is nicer output anyways, lot more info
