### ISSUE TITLE
Add version 1.6.8

### ISSUE THREAD

**Issue by r3dlight** [x90skysn3k/brutespray#40]
Hi,
By adding the new CHANGELOG.md file, you made two releases of the same version (implicitly hiding the old one) which is causing me problems with building the new debian package (I won't bother you with the details, but it's about generating the deltas on the pristine-tar git branch) so can I ask you to release a new 1.6.8 version so I can fix those problems?
Thank you for your help.

**Comment by x90skysn3k** [comment]
Hey!
Sorry about that, I just pushed v1.6.8.. let me know if that fixes it for you.
Thank you

**Comment by r3dlight** [comment]
That's perfect !
Thank you.
