### ISSUE TITLE
brutespray not parsing properly

### ISSUE THREAD

**Issue by gbiagomba** [x90skysn3k/brutespray#45]
Hello,

I ran brutespray against a target and it only scanned the ssh port even though the file had both ssh and ftp. The command i ran was identical to this one https://github.com/x90skysn3k/brutespray/issues/44 only i ran it on my ubuntu server

**Comment by x90skysn3k** [comment]
do you have the scan available? if it's not on a standard port try the -sV option for Nmap

**Comment by gbiagomba** [comment]
@x90skysn3k I can share the command but not the output. I'll see if I can clean the output of sensitive data

**Comment by x90skysn3k** [comment]
If you could just paste the part of the scan file that shows the server and port it missed.. for example 
`Host: 127.0.0.1 (localhost)	Ports: 22/open/tcp//ssh//OpenSSH 8.3p1 Debian 1 (protocol 2.0)/, 201/open/tcp//ftp//vsftpd 3.0.3/` etc.. feel free to obfuscate the version, IP address and hostname if needed

**Comment by gbiagomba** [comment]
Let me see if I can find the file in question because i was just feeding it a long list of files poured in from the find command lol

**Comment by gbiagomba** [comment]
here you go
```
Host: 127.0.0.1 (example.com)	Ports: 21/open/tcp//ftp///, 22/open/tcp//ssh///, 80/open/tcp//http///, 443/open/tcp//https///, 2222/open/tcp//EtherNetIP-1///, 8011/open/tcp//unknown///, 8012/open/tcp/////, 8013/open/tcp/////, 8014/open/tcp//unknown///, 8015/open/tcp//cfg-cloud///, 8016/open/tcp//ads-s///, 8017/open/tcp/////, 8018/open/tcp//unknown///, 8853/open/tcp/////
```

**Comment by x90skysn3k** [comment]
did you verify that it is actually FTP? i'd recommend making sure you scan with the `-sV` flag

**Comment by gbiagomba** [comment]
Hello, 

It looks to be working now, so i will be closing this ticket
