### ISSUE TITLE
Adding debug & verbose mode

### ISSUE THREAD

**Issue by gbiagomba** [x90skysn3k/brutespray#50]
Hey @x90skysn3k ,

would it be possible to add a verbose and debug flag to the tool? essentially it would be passing the `-w` and `-v` flag to medusa. So when brutespray hangs i can see what is going on. Relates to https://github.com/x90skysn3k/brutespray/issues/49

**Comment by x90skysn3k** [comment]
added medusa `-v` verbosity and `-w` for debug options

**Comment by gbiagomba** [comment]
@x90skysn3k thank you!
