### ISSUE TITLE
nessus  scan not working

### ISSUE THREAD

**Issue by hasanali586q** [x90skysn3k/brutespray#57]
`brutespray  --file  Host_discovery_FULL_mhifsw.nessus --threads 5 --threads 5 --hosts 5
`

run but problem error
```
No brutable services found.
 Please check your Nmap file.
```

**Comment by x90skysn3k** [comment]
what version are you running? That error looks to be from an older version that does not support .nessus files. You might try git cloning a copy of the latest version.

**Comment by hasanali586q** [comment]
brutespray.py v1.8                      
apt-get install brutespray

**Comment by x90skysn3k** [comment]
the error `Please check your Nmap file.` is not from version 1.8. I just tested a few .nessus files and i'm not seeing any problems. Can you post a screenshot of the error with the version?
