### ISSUE TITLE
Requirements for stock kali

### ISSUE THREAD

**Issue by crossmxn** [x90skysn3k/brutespray#6]
Im trying to run this on the latest stock kali linux vm provided by offensive security, is there anything I should do before running the script? When I try to run it it just exits. Below is what I see in the terminal.

root@kali:~/brutespray# python brutespray.py --file nmap.xml --threads 5 --hosts 5

                              #@                           @/              
                           @@@                               @@@           
                        %@@@                                   @@@.        
                      @@@@@                                     @@@@%      
                     @@@@@                                       @@@@@     
                    @@@@@@@                  @                  @@@@@@@    
                    @(@@@@@@@%            @@@@@@@            &@@@@@@@@@    
                    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@    
                     @@*@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ @@     
                       @@@( @@@@@#@@@@@@@@@*@@@,@@@@@@@@@@@@@@@  @@@       
                           @@@@@@ .@@@/@@@@@@@@@@@@@/@@@@ @@@@@@           
                                  @@@   @@@@@@@@@@@   @@@                  
                                 @@@@*  ,@@@@@@@@@(  ,@@@@                 
                                 @@@@@@@@@@@@@@@@@@@@@@@@@                 
                                  @@@.@@@@@@@@@@@@@@@ @@@                  
                                    @@@@@@ @@@@@ @@@@@@                    
                                       @@@@@@@@@@@@@                       
                                       @@   @@@   @@                       
                                       @@ @@@@@@@ @@                       
                                         @@% @  @@                 

        ██████╗ ██████╗ ██╗   ██╗████████╗███████╗███████╗██████╗ ██████╗  █████╗ ██╗   ██╗
        ██╔══██╗██╔══██╗██║   ██║╚══██╔══╝██╔════╝██╔════╝██╔══██╗██╔══██╗██╔══██╗╚██╗ ██╔╝
        ██████╔╝██████╔╝██║   ██║   ██║   █████╗  ███████╗██████╔╝██████╔╝███████║ ╚████╔╝ 
        ██╔══██╗██╔══██╗██║   ██║   ██║   ██╔══╝  ╚════██║██╔═══╝ ██╔══██╗██╔══██║  ╚██╔╝  
        ██████╔╝██║  ██║╚██████╔╝   ██║   ███████╗███████║██║     ██║  ██║██║  ██║   ██║   
        ╚═════╝ ╚═╝  ╚═╝ ╚═════╝    ╚═╝   ╚══════╝╚══════╝╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   
                                                                                   

 brutespray.py v1.5
 Created by: Shane Young/@x90skysn3k && Jacob Robles/@shellfail
 Inspired by: Leon Johnson/@sho-luv
 Credit to Medusa: JoMo-Kun / Foofus Networks <jmk@foofus.net>

Starting to brute, please make sure to use the right amount of threads(-t) and pStarting to brute, please make sure to use the right amount of threads(-t) and pStarting to brute, please make sure to use the right amount of threads(-t) and pStarting to brute, please make sure to use the right amount of threads(-t) and pStarting to brute, please make sure to use the right amount of threads(-t) and pStarting to brute, please make sure to use the right amount of threads(-t) and pStarting to brute, please make sure to use the right amount of threads(-t) and pStarting to brute, please make sure to use the right amount of threads(-t) and pStarting to brute, please make sure to use the right amount of threads(-t) and pStarting to brute, please make sure to use the right amount of threads(-t) and pStarting to brute, please make sure to use the right amount of threads(-t) and pStarting to brute, please make sure to use the right amount of threads(-t) and pStarting to brute, please make sure to use the right amount of threads(-t) and pStarting to brute, please make sure to use the right amount of threads(-t) and pStarting to brute, please make sure to use the right amount of threads(-t) and pStarting to brute, please make sure to use the right amount of threads(-t) and pStarting to brute, please make sure to use the right amount of threads(-t) and pStarting to brute, please make sure to use the right amount of threads(-t) and pStarting to brute, please make sure to use the right amount of threads(-t) and pStarting to brute, please make sure to use the right amount of threads(-t) and parallel hosts(-T)...  \

Brute-Forcing...     

root@kali:~/brutespray#

**Comment by x90skysn3k** [comment]
Could you do a git pull on the latest, and run it with the -i flag and send a screenshot? Sorry for the troubles

**Comment by crossmxn** [comment]
somehow is now working... I think it miiiiiiight be that now I used a more clean xml file... this time I only scanned for opened vnc port.... anyway, thanks a lot for your tool

**Comment by x90skysn3k** [comment]
yeah no problem, i'm closing the issue if that's okay!
