### ISSUE TITLE
Nmap output f*cks up..

### ISSUE THREAD

**Issue by nessuz** [x90skysn3k/brutespray#85]
Looks like my nmap output is going wrong.. could you give the right example cmd voor nmap with all (brutespray) supported services? I'm probily messing it up 😀 Thanks for the nice work!

**Comment by nessuz** [comment]
> It automatically pics out supported services. Thanks!

Then something is wrong with my output file.. what would be the right nmap command with the right output argument?

**Comment by x90skysn3k** [comment]
-oA and either using the gnmap or xml

**Comment by nessuz** [comment]
> -oA and either using the gnmap or xml 

nmap -sn 192.168.52.0/24 -oA -oX nmap.xml should be right?

**Comment by x90skysn3k** [comment]
Take out the -oX and extension of the file name and you should be good
