### ISSUE TITLE
support for cred list and custom interface

### ISSUE THREAD

**Issue by APT-ZERO** [x90skysn3k/brutespray#89]
Hello,
Could you please add support for credential combination list as input?
[username:passphrase] (first `:` will be separator because `:` is mostly not allowed in username but maybe used in passphrase)

And option to specify custom network interface to use for the process
Thank you.

**Comment by x90skysn3k** [comment]
I will work to integrate these into the next release

**Comment by x90skysn3k** [comment]
#v2.2.2 is slated to have combo list done, the dev branch has it finished up for now. The network interface will be a pretty big undertaking and may come in future versions with a proxy argument as well.
